# -*- coding: utf-8 -*-
"""hw2-5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dgrqRWR9z7JDKfxVG_92QCBa3PJcdP10

Задача 1:
Придумайте сложную алгебраическую функцию, там могут быть синусы и косинусы, возведения в степень и деления, всё, что вашей душе угодно. Напишите её с помощью def, чтобы она брала на вход x, а возвращала результат.
Сгенерируйте X- координаты точки с помощью np.linspace(), а Y получите, положив X в вашу функцию. Нарисуйте график, подпишите оси и сделайте подпись всей картинки(титульник). Сделайте так, чтобы на вашем графике были клеточки, график был пунктиром и зелёного цвета, а ещё полупрозрачным, и, чтобы к нему была подпись “Вот такая моя функция”.
"""

import numpy as np
import matplotlib.pyplot as plt

def my_function(x):
    return np.sin(x**2) / (np.cos(x)**2 + 1) + np.cos(x)

x = np.linspace(-5, 5, 100)
y = my_function(x)

plt.plot(x, y, linestyle='--', color='g', alpha=0.5)
plt.xlabel('X')
plt.ylabel('Y')
plt.text(0, 1.5, "Вот такая моя функция", ha='center')
plt.grid(True)
plt.show()

"""Задача 2:
Сгенерируйте данные следующим образом.
X = np.random.normal(0, 1, 3000)
Y = np.random.normal(3, 4, 3000)

Отобразите точки с помощью plt.scatter(). Подпишите оси и график, сделайте клеточки, укажите какой-нибудь размер точек, цвет и добавьте аргумент maker=’<’. Вместо < можете указать что-то своё. Укажите прозрачность, чтобы можно было увидеть, где много точек в одном месте, а где мало.

"""

import numpy as np
import matplotlib.pyplot as plt

X = np.random.normal(0, 1, 3000)
Y = np.random.normal(3, 4, 3000)

plt.scatter(X, Y, marker='*', alpha=0.5, s=20, c='b')
plt.title('Точки')
plt.xlabel('X')
plt.ylabel('Y')
plt.grid(True)
plt.show()

"""Задача 3.
Возможные результаты забега школьников на 100 метров можно сгенерировать следующим образом:
data = np.random.normal(16, 2, 1000)

Постройте гистограмму красного цвета с полупрозрачными столбиками. Какие выводы можно сделать о результатах по ней?

"""

import numpy as np
import matplotlib.pyplot as plt

data = np.random.normal(16, 2, 1000)

plt.hist(data, bins=50, color='r',alpha=0.5)
plt.title('Возможные результаты забега школьников на 100 метров')
plt.xlabel('время (сек)')
plt.ylabel('л')
plt.show()

"""большинство достигают времени в районе 16 секунд на дистанции в 100"""