# -*- coding: utf-8 -*-
"""hw-2-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MxhIwI7Yegz7HewEqzAoLk5qMRuO3qzv

Прочитайте представленный датасет(https://drive.google.com/drive/folders/1phOzEdwpLqxskFjRJSD-ZLRLk5Gh7DCz)(Подсказка: датасет надо сначала сохранить, а потом прочитать с помощию функции  read_csv)
"""

import pandas as pd

# Прочитать датасет из CSV файла
df = pd.read_csv('Customers2.csv', sep=';')

df

#Проверка данных на наличие пропусков
df.isnull().sum()

#удаление пропусков
df = df.dropna(subset=['Profession'])

#проверка на уникальность
df['Profession'].unique()

#Проверка данных на наличие пропусков после удаления
df.isnull().sum()

#Сгруппируйте данные по столбцу ‘Profession’ и найдите средний годовой доход в каждой группе
df.groupby('Profession')['Income'].mean()