# -*- coding: utf-8 -*-
"""дз 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LFaTfnL_RFjnWkDHwljN_LS3ye9Momhf
"""

# задача N1
a = float(input('введите число '))
b = int(input('введите число знаков после запятой '))
print(f"округленное число: {round(a,b)}")

# задача N2
a = float(input('введите число 1 '))
b = float(input('введите число 2 '))
c = (a + b)/2
print(f"округленное число: {round(c)}")